Delete team as captain leave and remove player for captain
devlup-labs/varchas pull request #15
Opened 2020-08-22 06:48 UTC by Garvit-32

This PR fixes #4 and #6

2020-08-25 14:02 UTC, Garvit-32 commented on registration/views.py
> +        userList.remove(team.captian)
file changed as per request and dropdown added 
![Annotation 2020-08-25 193011](https://user-images.githubusercontent.com/54506526/91183946-b411aa80-e709-11ea-8135-cc362c98cfda.png)

2020-08-26 00:56 UTC, harsh-not-haarsh commented on registration/views.py
> +        userList.remove(team.captian)
Looks good, Do this as well:

- [ ] Show "first_name (Email)" in the dropdown
- [ ] Get rid of the email list that is printed on the page

2020-08-26 00:59 UTC, harsh-not-haarsh requested changes

2020-08-26 00:59 UTC, harsh-not-haarsh commented on registration/views.py
> +        userList.remove(team.captian)
Looks good, Do this as well:

- [ ]  Show "first_name (Email)" in the dropdown
- [ ] Get rid of the email list that is printed on the page

2020-08-26 07:21 UTC, Garvit-32 commented on registration/views.py
> +        userList.remove(team.captian)
changes made as requested
![Annotation 2020-08-26 071411](https://user-images.githubusercontent.com/54506526/91273439-e28b9600-e79a-11ea-8922-752d8b785dc4.png)

2020-08-26 07:56 UTC, harsh-not-haarsh approved these changes

2020-08-26 07:57 UTC, merged