Google login feature added
devlup-labs/varchas pull request #19
Opened 2020-09-12 18:11 UTC by likhita24

2020-09-14 08:54 UTC, harsh-not-haarsh requested changes
Add screenshots to your PR as well

2020-09-14 08:54 UTC, harsh-not-haarsh commented on accounts/forms.py
> +class GoogleCreateProfileForm(forms.ModelForm):
@likhita24 
this method is same for creating profile via normal method right?
why not just name it CreateUserProfileForm or something?

2020-09-14 08:54 UTC, harsh-not-haarsh commented on accounts/urls.py
> +    path('googleregister/', views.GoogleCreateProfileView.as_view(), name='google-register'),
@likhita24 
People signing in using google will just need to register, people from the old method will also be required to create account. Use these two terms instead of what you currently have.

2020-09-14 08:55 UTC, harsh-not-haarsh commented
Also mention the Issue you are resolving in the description

2020-09-14 08:56 UTC, harsh-not-haarsh commented
Have a look at PR #15

2020-09-14 10:37 UTC, likhita24 commented on accounts/forms.py
> +class GoogleCreateProfileForm(forms.ModelForm):
No, creating profile via normal method comes with the registration process itself. When someone wants wants to sign up with google then they have to create a profile separately. So, I created a separate page for that and named the concerning view that way to show it's used in this case. This is how it looks, just the other details of the user.

![Screenshot (9)](https://user-images.githubusercontent.com/53465719/93075388-5981c380-f6a3-11ea-9e44-b38e1397c47a.png)

2020-09-17 09:31 UTC, harsh-not-haarsh commented on accounts/forms.py
> +class GoogleCreateProfileForm(forms.ModelForm):
@likhita24 
I think we discussed it in the call. The Create Profile part should be common for both.
If a person uses google, then he/she will only be required to create a profile. If someone uses the conventional way, they'll be first required to create a User (by filling a form for email, password, first name, last name etc) and then he/she will be prompted to the SAME Form to create a profile.

2020-09-17 09:34 UTC, harsh-not-haarsh commented
@likhita24 Since you have taken a different approach and the commit history is already messy (the flake8 errors), I am going to close this PR. When you do the requested changes, make a new PR

2020-09-17 09:34 UTC, closed without merging