Added google Authentication feature
devlup-labs/varchas pull request #23
Opened 2020-09-19 13:20 UTC by likhita24

As mentioned in the issue #16 , Added Google authentication feature using AllAuth library and also reformed the existing signup page by creating a separate create profile page.
Right now, the signup page looks like in the attached SS below

![Screenshot (11)](https://user-images.githubusercontent.com/53465719/93668215-bff25180-faa8-11ea-860e-4c9a61d616b7.png)
and the create profile page

![Screenshot (12)](https://user-images.githubusercontent.com/53465719/93668238-d7313f00-faa8-11ea-96a5-8ffa786b0bd4.png)

2020-09-19 14:02 UTC, harsh-not-haarsh requested changes

2020-09-19 14:02 UTC, harsh-not-haarsh commented on accounts/forms.py
> +
@likhita24 
You didn't add any validators here, add validators for phone number and referral code

2020-09-20 05:29 UTC, likhita24 commented on accounts/forms.py
> +
@harsh-not-haarsh 
Added Form validations for the create profile form

2020-09-29 16:55 UTC, harsh-not-haarsh requested changes

2020-09-29 16:55 UTC, harsh-not-haarsh commented on accounts/forms.py
> +class PasswordResetCaptchaForm(PasswordResetForm):
@likhita24 Maybe get rid of this right now?

2020-09-29 16:55 UTC, harsh-not-haarsh commented on accounts/forms.py
> +    username = forms.CharField(required=False)
@likhita24 Don't hardcode fields

2020-09-29 16:55 UTC, harsh-not-haarsh commented on accounts/forms.py
> +    phone = forms.CharField(max_length=13)
@likhita24 Don't hardcode the fields, import them from model only

2020-09-29 16:55 UTC, harsh-not-haarsh commented on client_secret_1083763914956-0jlme6quju4qqdbq4rfjh3n21nhiob0n.apps.googleusercontent.com.json
> +{"web":{"client_id":"1083763914956-0jlme6quju4qqdbq4rfjh3n21nhiob0n.apps.googleusercontent.com","project_id":"varchas","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oaut
shouldn't be a part of the repo

2020-09-29 16:55 UTC, harsh-not-haarsh commented on main/views.py
> +        if user.username != "":
@likhita24 You can check user.is_authenticated()

2020-09-29 16:55 UTC, harsh-not-haarsh commented on accounts/views.py
> +            profile = UserProfile(user=user, gender=data['gender'], phone=data['phone'],
this is not the best way to do it, you can just save the form.

2020-09-29 16:55 UTC, harsh-not-haarsh commented on accounts/views.py
> +        email = self.request.session['email']
just get user from request

2020-09-29 16:55 UTC, harsh-not-haarsh commented on accounts/views.py
> +def GoogleLogin(request):
The code should be abstract, rename google login to just login

2020-09-29 16:56 UTC, closed without merging