Remove Redundant TeamRegistrationForm1 from registration/forms.py
devlup-labs/varchas pull request #24
Opened 2020-09-21 05:56 UTC by Garvit-32

This PR fixes #21

2020-09-21 11:02 UTC, harsh-not-haarsh requested changes

2020-09-21 11:02 UTC, harsh-not-haarsh commented on registration/forms.py
> +        fields = ['sport', 'college', 'teamId']
@Garvit-32 I think we can remove teamId from here? Since there is no need for this in the form anyway.

2020-09-21 11:02 UTC, harsh-not-haarsh commented on registration/forms.py
> +
get rid of these comments?

2020-09-21 11:02 UTC, harsh-not-haarsh commented on registration/views.py
>              data = self.request.POST.copy()
also rewrite this function maybe? the way it is written is not efficient

2020-09-21 17:38 UTC, Garvit-32 commented on registration/forms.py
> +        fields = ['sport', 'college', 'teamId']
@harsh-not-haarsh changes made as requested

2020-09-22 03:20 UTC, harsh-not-haarsh requested changes
Make the overall code a bit cleaner and more readable

2020-09-22 03:20 UTC, harsh-not-haarsh commented on registration/views.py
>              data = self.request.POST.copy()
@Garvit-32 
We don't have to copy the data here right?

2020-09-22 03:20 UTC, harsh-not-haarsh commented on registration/views.py
>              form = TeamRegistrationForm(data)
@Garvit-32 we can get rid of this line as well

2020-09-22 03:23 UTC, harsh-not-haarsh commented on templates/registration/team.html
> +            {% if field.label != "TeamId" and field.label != "Captian" and field.label != "Sport" %}
@Garvit-32 We don't have to have to check for `captain` here since it is not a field of the form

2020-09-22 04:51 UTC, harsh-not-haarsh approved these changes

2020-09-22 04:52 UTC, merged